name: 'Install rlottie'
description: 'Installs the rlottie library'

inputs:
  shell:
    description: The shell to run the build-script with. Should be ash-compatible.
    required: false
    default: bash
  vendor:
    type: choice
    description: The vendor (GitHub organization) of the rlottie library.
    required: false
    options:
      - Samsung
      - TelegramMessenger
    default: Samsung
  version:
    description: The version of the rlottie library.
    required: false
  commit:
    description: The git commit of the rlottie library.
    required: false

runs:
  using: "composite"
  steps:
    - shell: ${{inputs.shell}}
      run: |
        git clone "https://github.com/${{inputs.vendor}}/rlottie"
        if [ -n "${{inputs.version}}" ]; then
          git checkout "v${{inputs.version}}"
        elif [ -n "${{inputs.tag}}" ]; then
          git checkout "${{inputs.commit}}"
        elif [ "${{inputs.vendor}}" == "Samsung" ]; then
          git checkout v0.2
        else
          git checkout 67f103bc8b625f2a4a9e94f1d8c7bd84c5a08d1d
        fi
        git checkout -b msrd0/install-rlottie-action
        
        # samsung version might need to be patched
        if ! git log --pretty=tformat:"%H" |grep 2d7b1fa2b005bba3d4b45e8ebfa632060e8a157a >/dev/null; then
          git cherry-pick 2d7b1fa2b005bba3d4b45e8ebfa632060e8a157a
        fi
        
        cd rlottie
        mkdir -p build
        cd build
        cmake .. \
          -DCMAKE_INSTALL_PREFIX=/usr \
          -DCMAKE_BUILD_TYPE=Release
        make -j2
        sudo make install
        cd ../..
        rm -r rlottie
